Remove reference to self.stations from net.py
self.stations is initialised in the Mininet_Wifi class but not in the Mininet class. Thus, this line caused a crash when using vanilla Mininet (AttributeError: 'Mininet' object has no attribute 'stations').